export const ALL_USERS = [
  {
    avatar: "https://docs.material-tailwind.com/img/face-1.jpg",
    userName: "Morsi",
    userId: 1,
    status: "Active",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-5.jpg",
    userName: "Nour",
    userId: 2,
    status: "Active",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-3.jpg",
    userName: "Merna",
    userId: 3,
    status: "Active",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-4.jpg",
    userName: "Abdelrahman",
    userId: 4,
    status: "",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-5.jpg",
    userName: "Emo",
    userId: 5,
    status: "",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-1.jpg",
    userName: "Morsi",
    userId: 6,
    status: "Active",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-5.jpg",
    userName: "Nour",
    userId: 7,
    status: "Active",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-3.jpg",
    userName: "Merna",
    userId: 8,
    status: "Active",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-4.jpg",
    userName: "Abdelrahman",
    userId: 9,
    status: "",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-5.jpg",
    userName: "Emo",
    userId: 10,
    status: "",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-1.jpg",
    userName: "Morsi",
    userId: 11,
    status: "Active",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-5.jpg",
    userName: "Nour",
    userId: 12,
    status: "Active",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-3.jpg",
    userName: "Merna",
    userId: 13,
    status: "Active",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-4.jpg",
    userName: "Abdelrahman",
    userId: 14,
    status: "",
  },
  {
    avatar: "https://docs.material-tailwind.com/img/face-5.jpg",
    userName: "Emo",
    userId: 15,
    status: "",
  },
];
export const MESSAGE = [
  {
    userId: 2,
    name: "ChatNook",
    avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
    text: "Hello ChatNookHello ChatNookHello ChatNookHello ChatNookHello ChatNookHello",
    date: "21:15",
    status: "bendging",
    id: "1",
  },
  {
    userId: 1,
    name: "Morsi",
    avatar: "https://docs.material-tailwind.com/img/face-1.jpg",
    text: "Lorem Ipsum is Lorem Ipsum and I am Lorem Ipsum Lorem Ipsum is Lorem Ipsum and I am Lorem Ipsum Lorem Ipsum is Lorem Ipsum and I am Lorem Ipsum ",
    date: "21:15",
    status: "bendging",
    id: "2",
  },
  {
    userId: 2,
    name: "ChatNook",
    avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
    text: "Hello Morsi",
    date: "21:15",
    status: "bndging",
    id: "3",
  },
  {
    userId: 1,
    name: "Morsi",
    avatar: "https://docs.material-tailwind.com/img/face-1.jpg",
    text: "Hello ChatNook",
    date: "21:15",
    status: "bending",
    id: "4",
  },
  {
    userId: 2,
    name: "ChatNook",
    avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
    text: "Hello ChatNookHello ChatNookHello ChatNookHello ChatNookHello ChatNookHello",
    date: "21:15",
    status: "bendging",
    id: "5",
  },
  {
    userId: 1,
    name: "Morsi",
    avatar: "https://docs.material-tailwind.com/img/face-1.jpg",
    text: "Lorem Ipsum is Lorem Ipsum and I am Lorem Ipsum Lorem Ipsum is Lorem Ipsum and I am Lorem Ipsum Lorem Ipsum is Lorem Ipsum and I am Lorem Ipsum ",
    date: "21:15",
    status: "bendging",
    id: "6",
  },
  {
    userId: 2,
    name: "ChatNook",
    avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
    text: "Hello Morsi",
    date: "21:15",
    status: "bndging",
    id: "7",
  },
  {
    userId: 1,
    name: "Morsi",
    avatar: "https://docs.material-tailwind.com/img/face-1.jpg",
    text: "Hello ChatNook",
    date: "21:15",
    status: "bending",
    id: "8",
  },
  {
    userId: 2,
    name: "ChatNook",
    avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
    text: "Hello ChatNookHello ChatNookHello ChatNookHello ChatNookHello ChatNookHello",
    date: "21:15",
    status: "bendging",
    id: "9",
  },
  {
    userId: 1,
    name: "Morsi",
    avatar: "https://docs.material-tailwind.com/img/face-1.jpg",
    text: "Lorem Ipsum is Lorem Ipsum and I am Lorem Ipsum Lorem Ipsum is Lorem Ipsum and I am Lorem Ipsum Lorem Ipsum is Lorem Ipsum and I am Lorem Ipsum ",
    date: "21:15",
    status: "bendging",
    id: "10",
  },
  {
    userId: 2,
    name: "ChatNook",
    avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
    text: "Hello Morsi",
    date: "21:15",
    status: "bndging",
    id: "11",
  },
  {
    userId: 1,
    name: "Morsi",
    avatar: "https://docs.material-tailwind.com/img/face-1.jpg",
    text: "Hello ChatNook",
    date: "21:15",
    status: "bending",
    id: "12",
  },
];
export const CHATS = [
  {
    chatId: "65f8b5349273ccc3a6a1d818",
    chatName: "Morsi",
    avatar: "https://docs.material-tailwind.com/img/face-1.jpg",
    messages: [],
  },
  {
    chatId: "9",
    chatName: "Abdo",
    avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
    messages: [],
  },
  {
    chatId: "8",
    chatName: "Emo",
    avatar: "https://docs.material-tailwind.com/img/face-3.jpg",
    messages: [],
  },
  {
    chatId: "7",
    chatName: "Nour",
    avatar: "https://docs.material-tailwind.com/img/face-5.jpg",
    messages: [],
  },
  {
    chatId: "6",
    chatName: "Merna",
    avatar: "https://docs.material-tailwind.com/img/face-5.jpg",
    messages: [],
  },
  {
    chatId: "5",
    chatName: "Hambozo",
    avatar: "https://docs.material-tailwind.com/img/face-4.jpg",
    messages: [],
  },
  {
    chatId: "4",
    chatName: "Hamada",
    avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
    messages: [],
  },
  {
    chatId: "3",
    chatName: "Sola",
    avatar: "https://docs.material-tailwind.com/img/face-3.jpg",
    messages: [],
  },
  {
    chatId: "2",
    chatName: "Mohamed",
    avatar: "https://docs.material-tailwind.com/img/face-4.jpg",
    messages: [],
  },
];
export const GET_USER_CHAT = [
  {
    _id: "65f8d1740c2b2342b9d75865",
    participants: [
      {
        _id: "65f8be68c780a42b3701ca38",
        fullName: "Hagar Saleh",
        email: "hager@gmail.com",
        profilePic: "https://i.ibb.co/xhbZ5fQ/download.png",
        createdAt: "2024-03-18T22:21:29.007Z",
        updatedAt: "2024-03-18T22:21:29.007Z",
        __v: 0,
        id: "65f8be68c780a42b3701ca38",
      },
      {
        _id: "65f77c79c13677f0895d0674",
        fullName: "Abdalrahman Gomaa",
        email: "abdo@gmail.com",
        profilePic: "https://i.ibb.co/xhbZ5fQ/download.png",
        createdAt: "2024-03-17T23:27:53.486Z",
        updatedAt: "2024-03-17T23:27:53.486Z",
        __v: 0,
        id: "65f77c79c13677f0895d0674",
      },
    ],
    lastMessage: {
      _id: "65f8d1980c2b2342b9d75871",
      senderId: "65f8be68c780a42b3701ca38",
      recieverId: "65f77c79c13677f0895d0674",
      chatId: "65f8d1740c2b2342b9d75865",
      message: "this is new to you",
      createdAt: "2024-03-18T23:43:21.146Z",
      updatedAt: "2024-03-18T23:43:21.146Z",
      __v: 0,
      id: "65f8d1980c2b2342b9d75871",
    },
    createdAt: "2024-03-18T23:42:44.167Z",
    updatedAt: "2024-03-18T23:43:20.990Z",
  },
];
